name: trace-cruncher CI

on:
  push:
    branches: [tracecruncher, yordan_devel]
  schedule:
    - cron:  '0 15 * * THU'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install build-essential git cmake libjson-c-dev binutils-dev -y
        sudo apt-get install libpython3-dev cython3 python3-numpy -y
        sudo apt install python3-pip
        sudo pip3 install --system pkgconfig GitPython
        git clone https://git.kernel.org/pub/scm/libs/libtrace/libtraceevent.git/
        cd libtraceevent
        make
        sudo make install
        cd ..
        git clone https://git.kernel.org/pub/scm/libs/libtrace/libtracefs.git/
        cd libtracefs
        make
        sudo make install
        cd ..
        git clone https://git.kernel.org/pub/scm/utils/trace-cmd/trace-cmd.git
        cd trace-cmd
        make
        sudo make install_libs
        cd ..
        git clone https://github.com/yordan-karadzhov/kernel-shark-v2.beta.git kernel-shark
        cd kernel-shark/build
        cmake ..
        make
        sudo make install
        cd ../..

    - name: Build
      working-directory: ${{runner.workspace}}/trace-cruncher
      shell: bash
      # Build and install.
      run: |
        make
        sudo make install

    - name: Test
      working-directory: ${{runner.workspace}}/trace-cruncher/tests
      shell: bash
      # Execute tests defined by the CMake configuration.
      run: sudo python3 -m unittest discover .
